NAME = phonebook

SRCS = Main.cpp PhoneBook.cpp Contacts.cpp
OBJS = $(SRCS:.cpp=.o)
CC = c++
CXXFLAGS = -Wall -Wextra -Werror -std=c++98

all: $(NAME)

$(NAME): $(OBJS)
	$(CXX) $(CXXFLAGS) -o $(NAME) $(OBJS)

clean:
	rm -f $(OBJS)

fclean: clean
	rm -f $(NAME)

re: fclean all
